# Project: ÏîÄ¿1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = test.o game.o
LINKOBJ  = test.o game.o
LIBS     = -L"C:/Softwares/Dev-Cpp/MinGW64/lib" -L"C:/Softwares/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Softwares/Dev-Cpp/MinGW64/include" -I"C:/Softwares/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Softwares/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Softwares/Dev-Cpp/MinGW64/include" -I"C:/Softwares/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Softwares/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Softwares/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = É¨À×.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

test.o: test.c
	$(CC) -c test.c -o test.o $(CFLAGS)

game.o: game.c
	$(CC) -c game.c -o game.o $(CFLAGS)
